version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: '${DB_NAME}'
    image: database-mysql:8.2
    container_name: database-mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    networks:
      - web-profile-api-network

  app:
    depends_on:
      - database-mysql
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: web-profile-api:latest
    container_name: web-profile-api
    ports:
      - "${PORT}:${PORT}"
    networks:
      - web-profile-api-network

volumes: 
  db:
networks:
  web-profile-api-network:
    driver: bridge
